# Generated by Django 6.0.2 on 2026-03-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_profesor', models.CharField(max_length=20, unique=True)),
                ('departamento', models.CharField(max_length=100)),
                ('tipo_contrato', models.CharField(max_length=50)),
            ],
        ),
    ]
