# Generated by Django 6.0.2 on 2026-04-22 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='tipo_contrato',
        ),
    ]
