# Generated by Django 6.0.2 on 2026-04-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_remove_personal_tipo_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='tipo_contrato',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
    ]
