# Generated by Django 6.0.2 on 2026-03-02 05:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_expiracion', models.DateField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
