# Generated by Django 6.0.2 on 2026-04-21 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credenciales', '0001_initial'),
        ('visitantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credencial',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credencial',
            name='visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitantes.visitante'),
        ),
    ]
