# Generated by Django 6.0.2 on 2026-03-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(max_length=20)),
                ('resultado', models.CharField(max_length=20)),
                ('dispositivo', models.CharField(max_length=100)),
            ],
        ),
    ]
