# Generated by Django 6.0.2 on 2026-03-02 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accesos', '0001_initial'),
        ('credenciales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceso',
            name='credencial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='credenciales.credencial'),
        ),
    ]
