# Generated by Django 6.0.2 on 2026-04-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceso',
            name='motivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
