# Generated by Django 6.0.2 on 2026-04-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('motivo', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
